package com.github.w4o.ticket.db.mapper;

import com.github.w4o.ticket.db.model.TicketRole;
import com.github.w4o.ticket.db.model.TicketRoleExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TicketRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    long countByExample(TicketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int deleteByExample(TicketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int insert(TicketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int insertSelective(TicketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    List<TicketRole> selectByExample(TicketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    TicketRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") TicketRole record, @Param("example") TicketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByExample(@Param("record") TicketRole record, @Param("example") TicketRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByPrimaryKeySelective(TicketRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByPrimaryKey(TicketRole record);
}