package com.github.w4o.ticket.db.mapper;

import com.github.w4o.ticket.db.model.TicketPermission;
import com.github.w4o.ticket.db.model.TicketPermissionExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TicketPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    long countByExample(TicketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int deleteByExample(TicketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int insert(TicketPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int insertSelective(TicketPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    List<TicketPermission> selectByExample(TicketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    TicketPermission selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") TicketPermission record, @Param("example") TicketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByExample(@Param("record") TicketPermission record, @Param("example") TicketPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByPrimaryKeySelective(TicketPermission record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByPrimaryKey(TicketPermission record);
}