package com.github.w4o.ticket.db.mapper;

import com.github.w4o.ticket.db.model.TicketAdminLoginLog;
import com.github.w4o.ticket.db.model.TicketAdminLoginLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TicketAdminLoginLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    long countByExample(TicketAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int deleteByExample(TicketAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int insert(TicketAdminLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int insertSelective(TicketAdminLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    List<TicketAdminLoginLog> selectByExample(TicketAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    TicketAdminLoginLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") TicketAdminLoginLog record, @Param("example") TicketAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByExample(@Param("record") TicketAdminLoginLog record, @Param("example") TicketAdminLoginLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByPrimaryKeySelective(TicketAdminLoginLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByPrimaryKey(TicketAdminLoginLog record);
}