package com.github.w4o.ticket.db.mapper;

import com.github.w4o.ticket.db.model.TicketAdminRoleRelation;
import com.github.w4o.ticket.db.model.TicketAdminRoleRelationExample;
import java.util.List;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface TicketAdminRoleRelationMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    long countByExample(TicketAdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int deleteByExample(TicketAdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int insert(TicketAdminRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int insertSelective(TicketAdminRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    List<TicketAdminRoleRelation> selectByExample(TicketAdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    TicketAdminRoleRelation selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByExampleSelective(@Param("record") TicketAdminRoleRelation record, @Param("example") TicketAdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByExample(@Param("record") TicketAdminRoleRelation record, @Param("example") TicketAdminRoleRelationExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByPrimaryKeySelective(TicketAdminRoleRelation record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ticket_admin_role_relation
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    int updateByPrimaryKey(TicketAdminRoleRelation record);
}