package com.github.w4o.ticket.db.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
public class TicketAdminLoginLog implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin_login_log.id
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin_login_log.admin_id
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Long adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin_login_log.create_time
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin_login_log.ip
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin_login_log.address
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin_login_log.user_agent
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String userAgent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_admin_login_log
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private static final long serialVersionUID = 1L;
}