package com.github.w4o.ticket.db.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
public class TicketAdmin implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.id
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.username
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.password
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.icon
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String icon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.email
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.nick_name
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String nickName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.note
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String note;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.create_time
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.login_time
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Date loginTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_admin.status
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_admin
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private static final long serialVersionUID = 1L;
}