package com.github.w4o.ticket.db.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
public class TicketRole implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_role.id
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_role.name
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_role.desc
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String desc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_role.enabled
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Boolean enabled;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_role.add_time
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_role.update_time
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_role.deleted
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_role
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private static final long serialVersionUID = 1L;
}