package com.github.w4o.ticket.db.model;

import java.io.Serializable;
import java.util.Date;
import lombok.Data;

@Data
public class TicketPermission implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_permission.id
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_permission.role_id
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Integer roleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_permission.permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private String permission;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_permission.add_time
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Date addTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_permission.update_time
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_permission.deleted
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private Boolean deleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ticket_permission
     *
     * @mbg.generated Fri May 10 14:52:53 CST 2019
     */
    private static final long serialVersionUID = 1L;
}